version: '3'
services:
  mysql:
   image: mysql-healthcheck
   ports:
      - "3307:3306"
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jpadb

  multitenancy-app:
    build: ./multitenancy-jpa-sample
    ports:
      - "8082:8082" 
    depends_on:
      - mysql       
    environment: 
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/jpadb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
 


